CREATE DATABASE IF NOT EXISTS DB_COMA_BEM;
USE DB_COMA_BEM;

CREATE TABLE TB_RESTAURANTES
(
	ID_RESTAURANTE INT(8)NOT NULL
   ,RES_NOME VARCHAR(60) NOT NULL
   ,RES_TIPO VARCHAR(60) NOT NULL
   ,RES_LONGITUDE VARCHAR(30)
   ,RES_LATITUDE VARCHAR(30)
   ,RES_RANKING DECIMAL(3,2)
   ,PRIMARY KEY (ID_RESTAURANTE)
);

CREATE TABLE TB_AVALIACOES
(
	ID_AVALIACAO INT(8) NOT NULL
   ,RES_ID INT(8) NOT NULL
   ,RES_NOME VARCHAR(60) NOT NULL
   ,RES_TIPO VARCHAR(60) NOT NULL
   ,RES_RANKING DECIMAL(3,2)
   ,AV_PRATO VARCHAR(60) NOT NULL
   ,AV_PRATO_FOTO BLOB
   ,AV_RANKING DECIMAL(3,2)
   ,AV_RECOMENDACAO VARCHAR(255)
   ,PRIMARY KEY (ID_AVALIACAO)
   ,FOREIGN KEY (RES_ID) REFERENCES TB_RESTAURANTES(ID_RESTAURANTE)
);